apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-config
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "piotrwierzykinpost": "task1"
    }
