apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-secret
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  SECRET_SALT: {{ randAlphaNum 8 | b64enc | quote }}
